DocumentRoot "C:/xampp/htdocs/HealthCare-System/public"
<Directory "C:/xampp/htdocs/HealthCare-System/public">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
